### ISSUE TITLE
Update the CI infrastructure to work with the new project/repositoty

### ISSUE THREAD

**Issue by snorbi07** [GoodGrind/ghostwriter#2]
The requirements for the CI environment are the same, only the repository that triggers the build has changed.

**Comment by szabolcsmaj** [comment]
Investigated if we could use the CI that gitlab provides. It can only be done in complex ways (cron jobs, pushing to both remote repos, etc) so I added back the old travis config and registered the product to use travis. Updated README.adoc to show the build status too.

One question remains: Do we still need to use the resulting artifacts for reporting purposes? This was implemented in gitlab but I'm not sure about github. Do we need to manually extract them or is there a smoother solution connected to travis/github?

**Comment by snorbi07** [comment]
Nope, this is good enough! Thanks!
