### ISSUE TITLE
Eliminate 3rd party libraries

### ISSUE THREAD

**Issue by szabolcsmaj** [GoodGrind/ghostwriter#23]
We should eliminate 3rd party libraries so users don't need to add unnecessary dependencies. Also they will cause trouble when there is a major version number difference between the runtime dependency and the dependency the users want to use in their own software. Is it a likely scenario?

Possible solution is to assemble the runtime jar including the dependencies under different package name to blow up JVM metaspace. Maybe we could provide 2 different jars?

**Comment by snorbi07** [comment]
Affects the runtime repos.
