### ISSUE TITLE
Setup a SonarQube instance for GhostWriter

### ISSUE THREAD

**Issue by szabolcsmaj** [GoodGrind/ghostwriter#28]
Provide a way to setup a  SonarQube  (https://sonarqube.com/), some high-level requirements:

 - can be hosted on a VPS provider
 - can be hosted locally in a VM or preferably Docker
 - can be bootstrapped with our custom ruleset (should be part of the provided image)
 - VPS hosted solution should be called for each GitLab commit

If  you provide an email address or create an account at DigitalOcean I can invite you to the team account. That way you can experiment with VPS setup as well.

**Comment by snorbi07** [comment]
For the current repo we use Codacy.
