### ISSUE TITLE
Provide an @Include annotation

### ISSUE THREAD

**Issue by otisonoza** [GoodGrind/ghostwriter#36]
Currently with the `@Exclude` annotation what is implemented is blacklisting.
The default is to trace every data unless an `@Exclude` annotation prevents it.

From a security perspective this is not ideal.
I'd not like to trace sensitive data accidentally.
A more ideal solution would be, if nothing is traced at all unless I annotate something with an `@Include` annotation for example.

This would also help with too big log files.
What I experience, that just after a few minutes the log files are so large I cannot even navigate in them.
Most of the stuff there are meaningless (getters, setters, etc.) which I excluded.
Again, an `@Include` driven approach here would be better.

**Comment by snorbi07** [comment]
hi @otisonoza,
By default the recommended approach is still the opt-out way since tracing runtime is just one of the provided solutions. Regardless, your concern can be addressed and supported through a settting so I'll add this to the next release.

**Comment by szabolcsmaj** [comment]
IIRC the original idea was to have the "trace-all unless `@Exclude`" approach by default and to include a switch in the settings or somewhere to change this approach to "trace-nothing unless `@Include`".

Regarding sensitive data: That's a different but connected task. The plan is to allow the users to define rulesets inside the settings to exclude certain data to be saved upon errors. These rulesets would be some kind of patterns to exclude variables/properties/classes/etc to be serialized that include certain expressions (SSN, password, CC number, etc).

**Comment by snorbi07** [comment]
@SLOBYYYY: yep, I'll add the "switch" in the context of this task of "instrument nothing unless Included".

**Comment by snorbi07** [comment]
Part of 0.5.0 release. Feel free to try it out and let me know if something is still missing
