### ISSUE TITLE
Special instrumentation of short methods

### ISSUE THREAD

**Issue by kuzuk** [GoodGrind/ghostwriter#46]
I propose to introduce a special mode of instrumentation that is used when a method size is under a configurable limit.
Reasoning: There are many short methods which, if instrumented as excessively as longer methods, will cause too much tracing. Such methods will also have a disproportionate impact on performance because tracing overhead. Therefore I think it makes sense to allow for a separate instrumentation mode for those methods.

There should be two configuration options:
- SHORT_METHOD_LIMIT: sets the size of methods, in number of statements, at or under which a different instrumentation is done. Proposed default: 3.
- SHORT_METHOD_TRACING: sets the instrumentation hooks to introduce. Options: RETURNING, VALUE_CHANGE, ON_ERROR, ENTERING_EXITING. Proposed default: RETURNING

The above defaults would mean that methods of 3 statements or less are only instrumented on the returning event.

**Comment by snorbi07** [comment]
Hi @kuzuk,
Seems like a reasonable request. One disclaimer though, that this is going to be an opt-in feature for now. I would only make it the default behavior if in practice this turns out to be a general improvement for both supported runtime implementations.

**Comment by snorbi07** [comment]
Small update here... next release will focus on the support for 'SHORT_METHOD_LIMIT' and it will be opt-in for now.
